apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 429881705512.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 429881705512.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 2728a193
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
